### ISSUE TITLE
slds fonts issue

### ISSUE THREAD

**Issue by harryheart** [nadrees/webpack-salesforce-plugin#1]
Hi Nathen,

I tried to package SalesforceSans fonts in the static resource and got following two warnings:
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
OTS parsing error: incorrect file size in WOFF header

After downloaded the static resource, I noticed the file sizes are different from original ones.
<img width="691" alt="screen shot 2016-12-14 at 4 58 20 pm" src="https://cloud.githubusercontent.com/assets/1230346/21175976/d49ac47a-c21f-11e6-9761-ae5ce622922d.png">

**Comment by nadrees** [comment]
@harryheart - sorry, i had my notifications set up to go to the wrong email address and didn't notice the issue being opened. Hopefully I can take a look over the next couple days and see what i can figure out.
